mode: deployment
replicaCount: 1
image:
  repository: otel/opentelemetry-collector-contrib

resources:
  limits:
    memory: 512Mi
  requests:
    memory: 256Mi

extraEnvs:
  - name: DASH0_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-authorization-token
  - name: DASH0_ENDPOINT_OTLP_GRPC_HOSTNAME
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-grpc-hostname
  - name: DASH0_ENDPOINT_OTLP_GRPC_PORT
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-grpc-port

presets:
  clusterMetrics:
    enabled: true
  kubernetesEvents:
    enabled: true
  kubernetesAttributes:
    enabled: true

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
    rabbitmq:
      endpoint: http://rabbitmq.dapr-demo.svc.cluster.local:15672
      username: guest
      password: guest
      collection_interval: 10s
      metrics:
        rabbitmq.node.disk_free:
          enabled: true
        rabbitmq.node.disk_free_limit:
          enabled: true
        rabbitmq.node.disk_free_alarm:
          enabled: true
        rabbitmq.node.mem_used:
          enabled: true
        rabbitmq.node.mem_limit:
          enabled: true
        rabbitmq.node.mem_alarm:
          enabled: true
        rabbitmq.node.fd_used:
          enabled: true
        rabbitmq.node.fd_total:
          enabled: true
        rabbitmq.node.sockets_used:
          enabled: true
        rabbitmq.node.sockets_total:
          enabled: true
        rabbitmq.node.proc_used:
          enabled: true
        rabbitmq.node.proc_total:
          enabled: true
        rabbitmq.node.disk_free_details.rate:
          enabled: true
        rabbitmq.node.fd_used_details.rate:
          enabled: true
        rabbitmq.node.mem_used_details.rate:
          enabled: true
        rabbitmq.node.proc_used_details.rate:
          enabled: true
        rabbitmq.node.sockets_used_details.rate:
          enabled: true
    prometheus:
      config:
        scrape_configs:
          - job_name: dapr-sidecars
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - action: keep
                regex: "true"
                source_labels:
                  - __meta_kubernetes_pod_annotation_dapr_io_enabled
              - action: replace
                replacement: $1
                source_labels:
                  - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                replacement: $1
                source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                regex: (.*);daprd
                replacement: $1-dapr
                source_labels:
                  - __meta_kubernetes_pod_annotation_dapr_io_app_id
                  - __meta_kubernetes_pod_container_name
                target_label: service
              - action: replace
                replacement: $1:9090
                source_labels:
                  - __meta_kubernetes_pod_ip
                target_label: __address__

          - job_name: dapr
            kubernetes_sd_configs:
              - role: pod
            relabel_configs:
              - action: keep
                regex: dapr
                source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_name
              - action: keep
                regex: dapr
                source_labels:
                  - __meta_kubernetes_pod_label_app_kubernetes_io_part_of
              - action: replace
                replacement: $1
                source_labels:
                  - __meta_kubernetes_pod_label_app
                target_label: app
              - action: replace
                replacement: $1
                source_labels:
                  - __meta_kubernetes_namespace
                target_label: namespace
              - action: replace
                replacement: $1
                source_labels:
                  - __meta_kubernetes_pod_name
                target_label: pod
              - action: replace
                replacement: $1:9090
                source_labels:
                  - __meta_kubernetes_pod_ip
                target_label: __address__  
  exporters:
    otlp/dash0:
      auth:
        authenticator: bearertokenauth/dash0
      endpoint: ${env:DASH0_ENDPOINT_OTLP_GRPC_HOSTNAME}:${env:DASH0_ENDPOINT_OTLP_GRPC_PORT}

  extensions:
    bearertokenauth/dash0:
      scheme: Bearer
      token: ${env:DASH0_AUTH_TOKEN}

  service:
    extensions:
      - bearertokenauth/dash0
      - health_check
    pipelines:
      logs:
        receivers:
          - otlp
        exporters:
          - otlp/dash0
      metrics:
        receivers:
          - otlp
          - prometheus
          - rabbitmq
          - k8s_cluster
        exporters:
          - otlp/dash0
      traces:
        receivers:
          - otlp
        exporters:
          - otlp/dash0