apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: dapr-demo
spec:
  type: NodePort
  ports:
    - name: "frontend"
      port: 3000
      targetPort: 80
      nodePort: 31000
  selector:
    app: frontend