apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-service
  name: notification-service
  namespace: dapr-demo
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 8082
      targetPort: 8082
  selector:
    app: notification-service