apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rabbitmq-consumer-scaler
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: rabbitmq-consumer
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 10
  pollingInterval: 5
  idleReplicaCount: 0
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: work_queue
      mode: QueueLength
      value: "5"
      host: amqp://guest:guest@rabbitmq.keda-demo.svc.cluster.local:5672/
      vhostName: /