operator:
  args:
    - --enable-prometheus-metrics=false
    - --enable-opentelemetry-metrics=true
  
  env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4318"
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "http/protobuf"
    - name: OTEL_SERVICE_NAME
      value: "keda-operator"