apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: demo
  labels:
    app: nodejs-app
spec:
  type: ClusterIP
  selector:
    app: nodejs-app
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP