---
apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: telemetry-policy
  namespace: agentgateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: ai-gateway
  frontend:
    tracing:
      backendRef:
        name: otel-collector-opentelemetry-collector
        namespace: opentelemetry
        port: 4317
      protocol: GRPC
      clientSampling: "true"
      randomSampling: "true"
      attributes:
        add:
          - name: environment
            expression: '"production"'
    accessLog:
      attributes:
        add:
          - name: gateway_name
            expression: '"ai-gateway"'
