---
# Gateway resource for agentgateway
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: agentgateway
  namespace: kagent
spec:
  gatewayClassName: agentgateway
  infrastructure:
    parametersRef:
      group: agentgateway.dev
      kind: AgentgatewayParameters
      name: tracing-config
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
      allowedRoutes:
        namespaces:
          from: Same
---
# HTTPRoute for A2A traffic to kagent controller
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kagent-a2a-route
  namespace: kagent
spec:
  parentRefs:
    - name: agentgateway
      namespace: kagent
  rules:
    - backendRefs:
        - name: kagent-controller
          port: 8083
---
# ConfigMap for agentgateway tracing configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: agentgateway-tracing-config
  namespace: kagent
data:
  config.yaml: |
    tracing:
      enabled: true
      otlpEndpoint: http://otel-collector-opentelemetry-collector.opentelemetry.svc.cluster.local:4317
      customFields:
        - key: gen_ai.system
          value: kagent
        - key: service.name
          value: agentgateway
