apiVersion: gateway.kgateway.dev/v1alpha1
kind: GatewayParameters
metadata:
  name: http-params
  namespace: kgateway-system
spec:
  kube:
    deployment:
      replicas: 1
    podTemplate:
      extraVolumes:
      - name: tmp
        emptyDir: {}
    envoyContainer:
      extraVolumeMounts:
      - name: tmp
        mountPath: /tmp
      env:
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "custom.test.attribute=test-value,custom.environment=kgateway-demo,custom.team=platform"
