apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: dapr-demo
data:
  enabled_plugins: |
      [rabbitmq_management,rabbitmq_prometheus,rabbitmq_amqp1_0].
  rabbitmq.conf: |
      # Clustering
      cluster_formation.peer_discovery_backend = classic_config
      
      # Memory configuration
      vm_memory_high_watermark.relative = 0.6
      
      # Disk free space
      disk_free_limit.relative = 2.0
      
      # Default user
      default_user = guest
      default_pass = guest
      
      # Allow guest user from any host (required for Dapr)
      loopback_users.guest = false
      
      # Management plugin configuration
      management.tcp.port = 15672
      
      # AMQP port
      listeners.tcp.default = 5672

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: dapr-demo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: dapr-demo
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
  selector:
    app: rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: dapr-demo
  labels:
    app: rabbitmq
spec:
  type: NodePort
  ports:
    - name: management
      port: 15672
      targetPort: 15672
      nodePort: 31672
  selector:
    app: rabbitmq

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: dapr-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9-management-alpine
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          resources:
            limits:
              cpu: "0.5"
              memory: "1Gi"
            requests:
              cpu: "0.1"
              memory: "256Mi"
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "ping"]
            initialDelaySeconds: 20
            timeoutSeconds: 10
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "status"]
            initialDelaySeconds: 60
            timeoutSeconds: 15
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config