apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-service
  name: todo-service
  namespace: dapr-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-service
  template:
    metadata:
      annotations:
        dapr.io/app-id: todo-service
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/config: "tracing"
        dapr.io/env: "OTEL_SERVICE_NAME=todo-service-daprd"
        instrumentation.opentelemetry.io/inject-java: "opentelemetry/instrumentation"
      labels:
        app: todo-service
    spec:
      containers:
        - image: localhost:5001/todo-service:v1
          name: todo-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SERVER_PORT
              value: "8080"