apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-service
  name: todo-service
  namespace: dapr-demo
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: todo-service