apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-app
  namespace: keda-demo
  labels:
    app: http-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-app
  template:
    metadata:
      labels:
        app: http-app
    spec:
      containers:
      - name: http-app
        image: http-app:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # OpenTelemetry configuration
        - name: OTEL_SERVICE_NAME
          value: "http-app"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector-opentelemetry-collector.opentelemetry:4318"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "http/protobuf"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: http-app
  namespace: keda-demo
spec:
  selector:
    app: http-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort