mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib

extraEnvs:
  - name: DASH0_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-authorization-token
  - name: DASH0_ENDPOINT_OTLP_GRPC_HOSTNAME
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-grpc-hostname
  - name: DASH0_ENDPOINT_OTLP_GRPC_PORT
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-grpc-port

# Need host network to collect host metrics
hostNetwork: true

# Run on all nodes including control-plane
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

config:
  receivers:
    hostmetrics:
      root_path: /hostfs
      scrapers:
        cpu:
        memory:
        load:
        disk:
        filesystem:
        network:
        paging:
        processes:
        process:

  exporters:
    otlp/dash0:
      endpoint: ${env:DASH0_ENDPOINT_OTLP_GRPC_HOSTNAME}:${env:DASH0_ENDPOINT_OTLP_GRPC_PORT}
      headers:
        Authorization: Bearer ${env:DASH0_AUTH_TOKEN}

  service:
    pipelines:
      metrics:
        receivers: [hostmetrics]
        exporters: [otlp/dash0]

# Mount host filesystem to collect host metrics
extraVolumes:
  - name: hostfs
    hostPath:
      path: /
      type: Directory

extraVolumeMounts:
  - name: hostfs
    mountPath: /hostfs
    readOnly: true
    mountPropagation: HostToContainer