mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib

extraEnvs:
  - name: DASH0_AUTH_TOKEN
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-authorization-token
  - name: DASH0_ENDPOINT_OTLP_GRPC_HOSTNAME
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-grpc-hostname
  - name: DASH0_ENDPOINT_OTLP_GRPC_PORT
    valueFrom:
      secretKeyRef:
        name: dash0-secrets
        key: dash0-grpc-port

# Host network for complete network interface metrics
hostNetwork: true

# Security context for accessing host metrics
securityContext:
  runAsUser: 0      # Required to read /proc files of other processes
  runAsGroup: 0
  capabilities:
    add:
      - SYS_PTRACE      # Required for process metrics
      - DAC_READ_SEARCH # Required for reading /proc files

# Run on all nodes including control-plane
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule

config:
  receivers:
    hostmetrics:
      root_path: /hostfs
      scrapers:
        cpu:
        memory:
        load:
        disk:
        filesystem:
        network:
        paging:
        processes:
        process:

  exporters:
    otlp/dash0:
      endpoint: ${env:DASH0_ENDPOINT_OTLP_GRPC_HOSTNAME}:${env:DASH0_ENDPOINT_OTLP_GRPC_PORT}
      headers:
        Authorization: Bearer ${env:DASH0_AUTH_TOKEN}

  service:
    pipelines:
      metrics:
        receivers: [hostmetrics]
        exporters: [otlp/dash0]

# Mount host filesystem to collect host metrics
extraVolumes:
  - name: hostfs
    hostPath:
      path: /
      type: Directory
  - name: passwd
    hostPath:
      path: /etc/passwd
      type: FileOrCreate

extraVolumeMounts:
  - name: hostfs
    mountPath: /hostfs
    readOnly: true
    mountPropagation: HostToContainer
  - name: passwd
    mountPath: /etc/passwd
    readOnly: true