apiVersion: v1
kind: Service
metadata:
  labels:
    app: validation-service
  name: validation-service
  namespace: dapr-demo
spec:
  type: ClusterIP
  ports:
    - name: "http"
      port: 8081
      targetPort: 8081
  selector:
    app: validation-service